# Generated by Django 4.1.1 on 2022-10-03 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regPage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regdata',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='regdata',
            name='password2',
        ),
    ]
