# Generated by Django 4.1.1 on 2022-10-21 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeuser',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
