# Generated by Django 4.1.1 on 2022-10-06 10:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('regPage', '0002_rename_password1_regdata_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=254)),
                ('dateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('Waiting for response', 'Waiting for response'), ('Answered', 'Answered'), ('Closed', 'Closed')], default='Waiting for response', max_length=20)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default=0, max_length=6)),
            ],
        ),
    ]
