# Generated by Django 4.1.1 on 2022-10-21 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regPage', '0002_alter_activeuser_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='activeuser',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
