# Generated by Django 4.1.1 on 2022-10-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regPage', '0003_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='dateTime',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='lastUpdate',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='state',
        ),
        migrations.AddField(
            model_name='ticket',
            name='discripton',
            field=models.TextField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(max_length=50),
        ),
    ]
