# Generated by Django 4.1.1 on 2022-10-21 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regPage', '0003_remove_activeuser_id_alter_activeuser_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeuser',
            name='TotalActiveTime',
            field=models.TimeField(null=True),
        ),
    ]
