# Generated by Django 4.1.1 on 2022-10-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regPage', '0004_activeuser_totalactivetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeuser',
            name='TotalActiveTime1',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
