# Generated by Django 4.1.1 on 2022-10-06 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regPage', '0004_remove_ticket_datetime_remove_ticket_lastupdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='discripton',
            new_name='descripton',
        ),
    ]
