# Generated by Django 4.1.1 on 2022-10-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regPage', '0005_rename_discripton_ticket_descripton'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='descripton',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=254),
        ),
    ]
