# Generated by Django 4.1.1 on 2022-10-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regPage', '0006_remove_activeuser_totalactivetime1'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='issueType',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
