# Generated by Django 3.2.16 on 2022-10-31 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regPage', '0009_ticket_title_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='title_id',
            new_name='ticket_id',
        ),
    ]
